"""Add remark field

Revision ID: 23e550a8b032
Revises: 0807abbe8c0e
Create Date: 2023-04-18 00:39:28.423309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e550a8b032'
down_revision = '0807abbe8c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
