"""Fix previous migration error

Revision ID: 2858f7a673bf
Revises: 23e550a8b032
Create Date: 2023-04-22 21:01:06.199604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2858f7a673bf'
down_revision = '23e550a8b032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_account_id', sa.Integer(), nullable=True))
        batch_op.drop_column('default_accunt_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_accunt_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('default_account_id')

    # ### end Alembic commands ###
