"""No activate field for user

Revision ID: 3be4d7b378d6
Revises: fba0e94af8b2
Create Date: 2023-03-19 14:57:44.744536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be4d7b378d6'
down_revision = 'fba0e94af8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
