"""role to enum

Revision ID: 48981fc7f942
Revises: 57cc8db4bb2d
Create Date: 2023-03-07 01:27:44.198348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48981fc7f942'
down_revision = '57cc8db4bb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'MISSION_RUNNER', 'MISSION_PUBLISHER', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'MISSION_RUNNER', 'MISSION_PUBLISHER', name='role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
