"""add esi_id field

Revision ID: 507943d96655
Revises: 2858f7a673bf
Create Date: 2023-04-28 18:56:33.217114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507943d96655'
down_revision = '2858f7a673bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esi_id', sa.Integer(), nullable=False))
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('esi_id')

    # ### end Alembic commands ###
