"""tracking

Revision ID: 57cc8db4bb2d
Revises: 2e59f46512eb
Create Date: 2023-03-06 23:17:52.094533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cc8db4bb2d'
down_revision = '2e59f46512eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('changed_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('prevous_value', sa.String(length=128), nullable=False),
    sa.Column('new_value', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_activity_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_changed_id'), ['changed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_table_name'), ['table_name'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lp_point', sa.Integer(), nullable=False))

    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounty', sa.Integer(), nullable=False))
        batch_op.drop_column('payable')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated')

    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payable', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('bounty')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('lp_point')
        batch_op.drop_column('activated')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_table_name'))
        batch_op.drop_index(batch_op.f('ix_activity_requester_id'))
        batch_op.drop_index(batch_op.f('ix_activity_changed_id'))

    op.drop_table('activity')
    # ### end Alembic commands ###
