"""Fix table by make default_accunt_id not a foreign key

Revision ID: d4d21b9f444f
Revises: f2b7cc524715
Create Date: 2023-04-14 00:01:00.976521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d21b9f444f'
down_revision = 'f2b7cc524715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_accunt_id_accounts', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_default_accunt_id_accounts', 'accounts', ['default_accunt_id'], ['id'])

    # ### end Alembic commands ###
