"""Changlog

Revision ID: fba0e94af8b2
Revises: 48981fc7f942
Create Date: 2023-03-07 23:34:02.415937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba0e94af8b2'
down_revision = '48981fc7f942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('attribute_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=False),
    sa.Column('new_value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log'))
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_log_requester_id'), ['requester_id'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_changed_id')
        batch_op.drop_index('ix_activity_requester_id')
        batch_op.drop_index('ix_activity_table_name')

    op.drop_table('activity')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)

    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requester_id', sa.INTEGER(), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('changed_id', sa.INTEGER(), nullable=False),
    sa.Column('attribute', sa.VARCHAR(length=64), nullable=False),
    sa.Column('prevous_value', sa.VARCHAR(length=128), nullable=False),
    sa.Column('new_value', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_activity_requester_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_activity')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_table_name', ['table_name'], unique=False)
        batch_op.create_index('ix_activity_requester_id', ['requester_id'], unique=False)
        batch_op.create_index('ix_activity_changed_id', ['changed_id'], unique=False)

    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_log_requester_id'))
        batch_op.drop_index(batch_op.f('ix_change_log_object_id'))

    op.drop_table('change_log')
    # ### end Alembic commands ###
